project:
  type: website
  output-dir: _site

website:
  title: "Closeread • Virginia Tech Demo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: zoom.qmd
        text: Zoom example
      - href: about.qmd
        text: About
  page-navigation: true

format:
  closeread-html:
    toc: false
    smooth-scroll: true
    theme:
      - styles/vt.scss     # <-- SCSS gets compiled here
    include-in-header: |
      <link rel="icon" href="images/vt-logo.svg">
