name: Build and Publish (Quarto + Closeread)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: quarto-dev/quarto-actions/setup@v2

      # Vendored install: no prompts, no waiting
      - name: Fetch Closeread extension (non-interactive)
        run: |
          mkdir -p _extensions/qmd-lab
          git clone --depth 1 https://github.com/qmd-lab/closeread tmp-closeread
          cp -r tmp-closeread/_extensions/closeread _extensions/qmd-lab/closeread

      - uses: quarto-dev/quarto-actions/render@v2

      - uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
